apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ace-create-integration-server-yaml-file
  namespace: ace01-ci
spec:
  description: Create App Connect Integration Server YAML
  params:
    - name: integration-name
      description: Name of the integration server.
    - name: ace-namespace
      description: Namespace of the ACE integration server.
    - name: ace-server-version
      description: Integration server version to be deployed.
    - name: ace-server-license
      description: License ID of Cloud Pak for Integration.
    - name: target-build-image
      description: Image URL referencing the docker image.
  workspaces:
    - name: output
  steps:
    - name: create-is-yaml
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/tools
      script: |
        #!/bin/sh
        echo "Create App Connect Integration Server YAML"

        # Generate Kubernetes artefacts from corresponding source artefacts
        cd $(workspaces.output.path)

        export NAME=$(params.integration-name)
        export NAMESPACE=$(params.ace-namespace)
        export LICENSE=$(params.license)
        export IMAGE_URL=$(params.image-url)
        export VERSION=$(params.version)

        envsubst < integrationserver.yaml.tmpl > integrationserver.yaml
        ls -l $(workspaces.output.path)
        cat ./integrationserver.yaml