apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ace-test
  namespace: ace01-ci
spec:
  workspaces:
    - name: source
      description: Tests ace01 integration server services
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "hello from ace-test task"

        # List Queue manager YAMLs
        cd $(workspaces.source.path)/repo/main

        # List YAMLs for each integration server service.
        cd config/yamls
        ls -alt *.yaml