apiVersion: v1
kind: ServiceAccount
metadata:
  name: ace-pipeline-deployer-serviceaccount
  namespace: ace01-ci
secrets:
  - name: gitcredentials-secret
imagePullSecrets:
  - name: ibm-entitlement-key