apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ace01-dev
  name: ace-deployer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "services"]
  verbs: ["*"]
- apiGroups: ["appconnect.ibm.com"] # mq.ibm.com API group - TBC
  resources: ["integrationservers", "configurations"] # TBC
  verbs: ["*"]
