apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig-secret
  namespace: ace01-ci
stringData:
  config.json: |
    {
      "auths" : {
        "image-registry.openshift-image-registry.svc.cluster.local:5000" : {
          "auth": "a3ViZWFkbWluOmJUQTRjLTY4UU1BLWNnR1VVLVhZOHJJ"
        }
      }
    }