apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ace01-ci
  name: pipeline-deployer
rules:
- apiGroups: ["tasks.tekton.dev"]
  resources: ["pipelines", "pipelinerunes", "tasks"]
  verbs: ["*"]
